// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6gLLlaz88AMro69kKJGBm18fIqfmW5Qs',
    appId: '1:379437741478:web:e85983090d4c7600d70b67',
    messagingSenderId: '379437741478',
    projectId: 'fireproject-c0d3b',
    authDomain: 'fireproject-c0d3b.firebaseapp.com',
    storageBucket: 'fireproject-c0d3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLh13rzLHF4RieIDrHt7m7xlW7Y_8i9M',
    appId: '1:379437741478:android:f2c9982aeec81f2bd70b67',
    messagingSenderId: '379437741478',
    projectId: 'fireproject-c0d3b',
    storageBucket: 'fireproject-c0d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQEtDddjXvn8HcT2yRPPpwZ9955vY1PA',
    appId: '1:379437741478:ios:974599b677c543ecd70b67',
    messagingSenderId: '379437741478',
    projectId: 'fireproject-c0d3b',
    storageBucket: 'fireproject-c0d3b.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQEtDddjXvn8HcT2yRPPpwZ9955vY1PA',
    appId: '1:379437741478:ios:974599b677c543ecd70b67',
    messagingSenderId: '379437741478',
    projectId: 'fireproject-c0d3b',
    storageBucket: 'fireproject-c0d3b.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6gLLlaz88AMro69kKJGBm18fIqfmW5Qs',
    appId: '1:379437741478:web:26f0e94d52420145d70b67',
    messagingSenderId: '379437741478',
    projectId: 'fireproject-c0d3b',
    authDomain: 'fireproject-c0d3b.firebaseapp.com',
    storageBucket: 'fireproject-c0d3b.appspot.com',
  );
}
